#!/bin/sh

rm -rf /tmp/upgrade
/etc/init.d/liconspgsh stop
rm -rf /usr/licon

if [ -z "$1" ]
then
        echo "Please input link,eg: upgrade your-urtl"
        exit 2
else
        #download file
        mkdir -p /tmp/upgrade
        wget -P /tmp/upgrade $1

        tar -xvf /tmp/upgrade/licon.tar -C /tmp/upgrade
        mv /tmp/upgrade/licon /usr/
        /etc/init.d/liconspgsh restart
fi

